<?php

declare(strict_types=1);

namespace BetterMagento\ModuleAudit\Model\Export;

use BetterMagento\ModuleAudit\Api\Data\AuditReportInterface;
use BetterMagento\ModuleAudit\Api\Export\ExporterInterface;

/**
 * Export audit reports as HTML.
 *
 * Produces professional, styled HTML reports suitable for:
 * - Executive presentations
 * - Client deliverables
 * - Print documentation
 * - Browser viewing
 */
class HtmlExporter implements ExporterInterface
{
    /**
     * Export audit report as HTML.
     */
    public function export(AuditReportInterface $report): string
    {
        $html = $this->buildHtmlStructure($report);
        return $html;
    }

    public function getMimeType(): string
    {
        return 'text/html';
    }

    public function getFileExtension(): string
    {
        return 'html';
    }

    /**
     * Build complete HTML document.
     */
    private function buildHtmlStructure(AuditReportInterface $report): string
    {
        $stats = $report->getStatistics();
        $score = $report->getScore();
        $grade = $report->getGrade();
        $gradeColor = $this->getGradeColor($grade);

        $html = <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BetterMagento Module Audit Report</title>
    <style>
        {$this->getCss()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>BetterMagento Module Audit Report</h1>
            <p class="timestamp">Generated: {$report->getExecutedAt()}</p>
        </header>

        <section class="summary">
            <div class="score-card" style="border-color: {$gradeColor}">
                <div class="score-value">{$score}</div>
                <div class="score-label">Score</div>
                <div class="grade" style="color: {$gradeColor}">Grade: {$grade}</div>
            </div>
        </section>

        <section class="statistics">
            <h2>Statistics Overview</h2>
            
            <div class="stats-grid">
                <div class="stat-card">
                    <h3>Modules</h3>
                    <table>
                        <tr><td>Total Modules</td><td>{$stats['total_modules']}</td></tr>
                        <tr><td>Enabled Modules</td><td>{$stats['enabled_modules']}</td></tr>
                        <tr><td>With Routes</td><td>{$stats['modules_with_routes']}</td></tr>
                        <tr><td>With Observers</td><td>{$stats['modules_with_observers']}</td></tr>
                        <tr><td>With Plugins</td><td>{$stats['modules_with_plugins']}</td></tr>
                        <tr><td>With Cron</td><td>{$stats['modules_with_cron']}</td></tr>
                    </table>
                </div>

                <div class="stat-card">
                    <h3>Observers</h3>
                    <table>
                        <tr><td>Total Observers</td><td>{$stats['total_observers']}</td></tr>
                        <tr><td>High-Frequency</td><td class="warning">{$stats['high_frequency_observers']}</td></tr>
                        <tr><td>Invalid</td><td class="error">{$stats['invalid_observers']}</td></tr>
                    </table>
                </div>

                <div class="stat-card">
                    <h3>Plugins</h3>
                    <table>
                        <tr><td>Total Plugins</td><td>{$stats['total_plugins']}</td></tr>
                        <tr><td>Around Plugins</td><td class="warning">{$stats['around_plugins']}</td></tr>
                        <tr><td>Deep Chains (≥4)</td><td class="error">{$stats['deep_chains']}</td></tr>
                    </table>
                </div>
            </div>
        </section>

        {$this->buildTopIssuesSection($report)}
        {$this->buildModulesSection($report)}
        {$this->buildObserversSection($report)}
        {$this->buildPluginsSection($report)}

        <footer>
            <p>Report generated by <strong>BetterMagento Module Audit v1.0</strong></p>
            <p>For more information, visit <a href="https://bettermagento.com">bettermagento.com</a></p>
        </footer>
    </div>
</body>
</html>
HTML;

        return $html;
    }

    /**
     * Build top issues section.
     */
    private function buildTopIssuesSection(AuditReportInterface $report): string
    {
        $issues = $this->collectTopIssues($report);

        if (empty($issues)) {
            return <<<HTML
            <section class="top-issues">
                <h2>Top Issues</h2>
                <p class="success">✓ No major performance issues detected</p>
            </section>
            HTML;
        }

        $rows = '';
        foreach (array_slice($issues, 0, 15) as $issue) {
            $severityClass = match($issue['severity']) {
                'high' => 'error',
                'medium' => 'warning',
                default => 'info'
            };

            $rows .= <<<HTML
                <tr class="{$severityClass}">
                    <td>{$issue['type']}</td>
                    <td>{$issue['score']}</td>
                    <td>{$issue['module']}</td>
                    <td>{$issue['description']}</td>
                </tr>
            HTML;
        }

        return <<<HTML
        <section class="top-issues">
            <h2>Top Issues (Top 15)</h2>
            <table>
                <thead>
                    <tr>
                        <th>Type</th>
                        <th>Score</th>
                        <th>Module</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    {$rows}
                </tbody>
            </table>
        </section>
        HTML;
    }

    /**
     * Build modules section.
     */
    private function buildModulesSection(AuditReportInterface $report): string
    {
        $rows = '';
        foreach ($report->getModules() as $module) {
            $scoreClass = $module->getScore() >= 5 ? 'warning' : '';
            $features = [];
            if ($module->hasRoutes()) $features[] = 'Routes';
            if ($module->hasObservers()) $features[] = 'Observers';
            if ($module->hasPlugins()) $features[] = 'Plugins';
            if ($module->hasCron()) $features[] = 'Cron';
            $featuresStr = implode(', ', $features) ?: 'None';

            $rows .= <<<HTML
                <tr class="{$scoreClass}">
                    <td>{$module->getName()}</td>
                    <td>{$module->getVersion()}</td>
                    <td>{$module->getScore()}</td>
                    <td>{$featuresStr}</td>
                    <td>{$module->getRecommendation()}</td>
                </tr>
            HTML;
        }

        return <<<HTML
        <section class="modules">
            <h2>Module Details</h2>
            <table>
                <thead>
                    <tr>
                        <th>Module Name</th>
                        <th>Version</th>
                        <th>Score</th>
                        <th>Features</th>
                        <th>Recommendation</th>
                    </tr>
                </thead>
                <tbody>
                    {$rows}
                </tbody>
            </table>
        </section>
        HTML;
    }

    /**
     * Build observers section.
     */
    private function buildObserversSection(AuditReportInterface $report): string
    {
        $rows = '';
        foreach ($report->getObservers() as $observer) {
            $scoreClass = $observer->getScore() >= 6 ? 'warning' : '';
            if (!$observer->isValid()) $scoreClass = 'error';

            $rows .= <<<HTML
                <tr class="{$scoreClass}">
                    <td>{$observer->getModuleName()}</td>
                    <td>{$observer->getEventName()}</td>
                    <td>{$observer->getObserverClass()}</td>
                    <td>{$observer->getScore()}</td>
                    <td>{$this->formatBoolean($observer->isHighFrequency())}</td>
                    <td>{$this->formatBoolean($observer->isValid())}</td>
                </tr>
            HTML;
        }

        return <<<HTML
        <section class="observers">
            <h2>Observer Details</h2>
            <table>
                <thead>
                    <tr>
                        <th>Module</th>
                        <th>Event</th>
                        <th>Observer Class</th>
                        <th>Score</th>
                        <th>High-Freq</th>
                        <th>Valid</th>
                    </tr>
                </thead>
                <tbody>
                    {$rows}
                </tbody>
            </table>
        </section>
        HTML;
    }

    /**
     * Build plugins section.
     */
    private function buildPluginsSection(AuditReportInterface $report): string
    {
        $rows = '';
        foreach ($report->getPlugins() as $plugin) {
            $scoreClass = $plugin->getScore() >= 7 ? 'warning' : '';
            if ($plugin->getChainDepth() >= 4) $scoreClass = 'error';

            $rows .= <<<HTML
                <tr class="{$scoreClass}">
                    <td>{$plugin->getModuleName()}</td>
                    <td>{$plugin->getInterceptedClass()}</td>
                    <td>{$plugin->getPluginClass()}</td>
                    <td>{$plugin->getPluginType()}</td>
                    <td>{$plugin->getChainDepth()}</td>
                    <td>{$plugin->getScore()}</td>
                </tr>
            HTML;
        }

        return <<<HTML
        <section class="plugins">
            <h2>Plugin Details</h2>
            <table>
                <thead>
                    <tr>
                        <th>Module</th>
                        <th>Intercepted Class</th>
                        <th>Plugin Class</th>
                        <th>Type</th>
                        <th>Chain Depth</th>
                        <th>Score</th>
                    </tr>
                </thead>
                <tbody>
                    {$rows}
                </tbody>
            </table>
        </section>
        HTML;
    }

    /**
     * Collect top issues from report.
     *
     * @return array<int, array<string, mixed>>
     */
    private function collectTopIssues(AuditReportInterface $report): array
    {
        $issues = [];

        foreach ($report->getObservers() as $observer) {
            if ($observer->isHighFrequency() && $observer->getScore() >= 6) {
                $issues[] = [
                    'type' => 'Observer',
                    'severity' => 'high',
                    'score' => $observer->getScore(),
                    'module' => $observer->getModuleName(),
                    'description' => "High-frequency observer on \"{$observer->getEventName()}\"",
                ];
            }
        }

        foreach ($report->getPlugins() as $plugin) {
            if ($plugin->getScore() >= 7) {
                $issues[] = [
                    'type' => 'Plugin',
                    'severity' => $plugin->getScore() >= 8 ? 'high' : 'medium',
                    'score' => $plugin->getScore(),
                    'module' => $plugin->getModuleName(),
                    'description' => "{$plugin->getPluginType()} plugin intercepts {$plugin->getInterceptedClass()}",
                ];
            }
        }

        foreach ($report->getModules() as $module) {
            if ($module->getScore() >= 7) {
                $issues[] = [
                    'type' => 'Module',
                    'severity' => 'medium',
                    'score' => $module->getScore(),
                    'module' => $module->getName(),
                    'description' => 'Unused or underutilized module',
                ];
            }
        }

        usort($issues, fn($a, $b) => $b['score'] <=> $a['score']);
        return $issues;
    }

    /**
     * Format boolean as Yes/No.
     */
    private function formatBoolean(bool $value): string
    {
        return $value ? '✓ Yes' : '✗ No';
    }

    /**
     * Get color for grade.
     */
    private function getGradeColor(string $grade): string
    {
        return match($grade) {
            'A' => '#22c55e',
            'B' => '#84cc16',
            'C' => '#eab308',
            'D' => '#f97316',
            'E', 'F' => '#ef4444',
            default => '#6b7280'
        };
    }

    /**
     * Get embedded CSS.
     */
    private function getCss(): string
    {
        return <<<CSS
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; line-height: 1.6; color: #1f2937; background: #f9fafb; }
        .container { max-width: 1200px; margin: 0 auto; padding: 2rem; }
        header { text-align: center; margin-bottom: 3rem; padding: 2rem; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; border-radius: 12px; }
        header h1 { font-size: 2.5rem; margin-bottom: 0.5rem; }
        .timestamp { opacity: 0.9; font-size: 0.95rem; }
        section { background: white; padding: 2rem; margin-bottom: 2rem; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
        h2 { color: #111827; margin-bottom: 1.5rem; font-size: 1.75rem; border-bottom: 3px solid #667eea; padding-bottom: 0.5rem; }
        h3 { color: #374151; margin-bottom: 1rem; font-size: 1.25rem; }
        .summary { text-align: center; }
        .score-card { display: inline-block; padding: 2rem 3rem; border: 4px solid; border-radius: 12px; }
        .score-value { font-size: 4rem; font-weight: bold; line-height: 1; }
        .score-label { font-size: 1rem; color: #6b7280; margin-bottom: 0.5rem; }
        .grade { font-size: 1.5rem; font-weight: bold; margin-top: 0.5rem; }
        .stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 1.5rem; }
        .stat-card { padding: 1.5rem; border: 1px solid #e5e7eb; border-radius: 8px; }
        table { width: 100%; border-collapse: collapse; margin-top: 1rem; }
        th { background: #f3f4f6; padding: 0.75rem; text-align: left; font-weight: 600; border-bottom: 2px solid #d1d5db; }
        td { padding: 0.75rem; border-bottom: 1px solid #e5e7eb; }
        tr:hover { background: #f9fafb; }
        .warning { background: #fef3c7 !important; }
        .error { background: #fee2e2 !important; }
        .success { color: #22c55e; font-size: 1.1rem; padding: 1rem; background: #f0fdf4; border-left: 4px solid #22c55e; }
        .info { color: #3b82f6; }
        footer { text-align: center; margin-top: 3rem; padding: 2rem; color: #6b7280; border-top: 1px solid #e5e7eb; }
        footer a { color: #667eea; text-decoration: none; }
        @media print { body { background: white; } .container { padding: 0; } section { box-shadow: none; page-break-inside: avoid; } }
        CSS;
    }
}
